module Keys
  SHARED_KEY = '8dqK8Vcio6cpMIZxB07eA'
  SHARED_SECRET = 'o0l3uIIBbKwgEn0Mx7rEeGHS2NoVRfaxV4oWHOdg'
  
  REQUEST_TOKEN = 'nXkaWXgNvnA5TnpSKelcZQ'
  REQUEST_SECRET = '80wM5RoYjiqa1czv5sFRjWXKhICgTNM5FBRzHKZQ2k'
  
  ACCESS_TOKEN = 'OAF9nsv3qKn4xZK7bJ1jdQ'
  ACCESS_SECRET = '9PPiC3f9EoycKiHg1zkUXiZbvLXQCUXl8Iy7qg21jk'
end
